baseURL = "https://fangrecording.com/"
languageCode = "en-us"
title = "Fang Recording"
theme = "Fang"
enableInlineShortcodes = true
pluralizelisttitles = false

[[menu.main]]
    url = "mailto:fangrecording@gmail.com"
    name = "Contact"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://instagram.com/fangrecording/"
    name = "fab fa-instagram"
    weight = 2

[[menu.icon]]
    url = "https://open.spotify.com/user/knbbyjp2jmme2mhmdgeno1tuc"
    name = "fab fa-spotify"
    weight = 3
