backend:
  name: git-gateway
  branch: main
media_folder: "/static/images/"
public_folder: "/images/"
logo_url: https://fangrecording.com/images/fang-recording_white.svg
dispaly_url: https://fangrecording.com
site_url: https://fangrecording.com
collections:
  - name: "gallery"
    label: "Gallery"
    folder: "/content/gallery"
    media_folder: "/content/gallery/img"
    public_folder: "/gallery/img"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "About"
    name: "about"
    folder: "/content/about"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "Clients"
    name: "clients"
    folder: "/content/clients"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - label: "Gear"
    name: "gear"
    folder: "/content/gear"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
